In [ ]:
%pip install -q \
  numpy pandas matplotlib PyQt6 tqdm scikit-learn scikit-image \
  torch torchvision torchaudio torchmetrics \
  transformers sentencepiece datasets accelerate evaluate rouge_score \
  graphviz openpyxl \
  mypy isort yapf coverage pytest

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 31.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 35.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 69.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.1/254.1 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 MB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.1/301.1 kB 17.1 MB/s eta 0:00:00


**Task 1**

In [2]:
import numpy as np


def main() -> None:
    # Sunday analysis
    baseball = [180, 215, 210, 210, 188, 176, 209, 200]
    baseball_arr = np.array(baseball)

    print("Sunday analysis:")
    print("Baseball array:", baseball_arr)
    print("Type of baseball array:", type(baseball_arr))

    # Monday analysis
    height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70,
                 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73,
                 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77,
                 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75,
                 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75,
                 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74,
                 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72,
                 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74,
                 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73,
                 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76,
                 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71,
                 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73,
                 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72,
                 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75,
                 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72,
                 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74,
                 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76,
                 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76,
                 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73,
                 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75,
                 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75,
                 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74,
                 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75,
                 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72,
                 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74,
                 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74,
                 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72,
                 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73,
                 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72,
                 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76,
                 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74,
                 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71,
                 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77,
                 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71,
                 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74,
                 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75,
                 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76,
                 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71,
                 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75,
                 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75,
                 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72,
                 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70,
                 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73,
                 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77,
                 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72,
                 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75,
                 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70,
                 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76,
                 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71,
                 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74,
                 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72,
                 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75,
                 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75,
                 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72,
                 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73,
                 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72,
                 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74,
                 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70,
                 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75,
                 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70,
                 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76,
                 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74,
                 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75,
                 72, 75, 73, 74, 75, 75, 73]

    np_height_in = np.array(height_in)
    np_height_m = np_height_in * 0.0254

    print(f'{np_height_in=}')



if __name__ == '__main__':
    main()


Sunday analysis:
Baseball array: [180 215 210 210 188 176 209 200]
Type of baseball array: <class 'numpy.ndarray'>
np_height_in=array([74, 74, 72, ..., 75, 75, 73])


**Task 2**

In [ ]:
import sys, os
sys.path.append("/content/sample_data")

import numpy as np
from baseball_dataset import baseball_dataset
from baseball_dataset_corrected import baseball_dataset_corrected


def main() -> None:
    np_baseball = np.array(baseball_dataset, dtype=float)

    print(f"Number of rows and columns: {np_baseball.shape}")

    height = np_baseball[:, 0]
    weight = np_baseball[:, 1]
    age = np_baseball[:, 2]

    print("Summary statistics for height:")
    print(f"  min: {height.min():.2f}, max: {height.max():.2f}, mean: {height.mean():.2f}")
    print("Summary statistics for weight:")
    print(f"  min: {weight.min():.2f}, max: {weight.max():.2f}, mean: {weight.mean():.2f}")
    print("Summary statistics for age:")
    print(f"  min: {age.min():.2f}, max: {age.max():.2f}, mean: {age.mean():.2f}")

    # Q1 answer:
    # In the raw data, the height column has impossible values like 74000.0,
    # 73000.0, 72000.0, 75000.0 inches, so the MLB data is clearly abnormal.

    # ---- CORRECTED DATA ----
    np_baseball_corr = np.array(baseball_dataset_corrected, dtype=float)
    h_corr = np_baseball_corr[:, 0]
    w_corr = np_baseball_corr[:, 1]
    a_corr = np_baseball_corr[:, 2]

    print("\nAfter data correction:")
    print("Summary statistics for height:")
    print(f"  min: {h_corr.min():.2f}, max: {h_corr.max():.2f}, mean: {h_corr.mean():.2f}")
    print("Summary statistics for weight:")
    print(f"  min: {w_corr.min():.2f}, max: {w_corr.max():.2f}, mean: {w_corr.mean():.2f}")
    print("Summary statistics for age:")
    print(f"  min: {a_corr.min():.2f}, max: {a_corr.max():.2f}, mean: {a_corr.mean():.2f}")

    # Extra statistics to answer: "Do big players tend to be heavier?"
    corr_hw = np.corrcoef(h_corr, w_corr)[0, 1]
    print("\nHeight–weight relationship (corrected data):")
    print(f"  Pearson correlation between height and weight: {corr_hw:.3f}")

    median_height = np.median(h_corr)
    taller = h_corr >= median_height
    shorter = ~taller

    print(f"  Mean weight for shorter half: {w_corr[shorter].mean():.2f}")
    print(f"  Mean weight for taller  half: {w_corr[taller].mean():.2f}")

    # Q2 answer:
    # The correlation between height and weight is clearly positive, and
    # the taller half of players has a higher mean weight than the shorter half.
    # So yes, bigger players do tend to be heavier.


if __name__ == "__main__":
    main()


Number of rows and columns: (1015, 3)
Summary statistics for height:
  min: 67.00, max: 76000.00, mean: 1586.46
Summary statistics for weight:
  min: 150.00, max: 290.00, mean: 201.35
Summary statistics for age:
  min: 20.90, max: 48.52, mean: 28.71

After data correction:
Summary statistics for height:
  min: 67.00, max: 83.00, mean: 73.69
Summary statistics for weight:
  min: 150.00, max: 290.00, mean: 201.35
Summary statistics for age:
  min: 20.90, max: 48.52, mean: 28.71

Height–weight relationship (corrected data):
  Pearson correlation between height and weight: 0.532
  Mean weight for shorter half: 191.71
  Mean weight for taller  half: 209.99


In [ ]:
import sys, os
print(os.listdir("/content/sample_data"))  # should list baseball_dataset.py etc.
sys.path.append("/content/sample_data")

import numpy as np

try:
    from baseball_dataset import baseball_dataset
    from baseball_dataset_corrected import baseball_dataset_corrected
    print("Imports succeeded, length of baseball_dataset:", len(baseball_dataset))
except ModuleNotFoundError as e:
    print("ModuleNotFoundError:", e)


['anscombe.json', 'README.md', 'mnist_train_small.csv', 'california_housing_test.csv', 'mnist_test.csv', 'california_housing_train.csv']
Imports succeeded, length of baseball_dataset: 1015


**Task 3: Import NumPy**

In [ ]:
import numpy as np

**Task 4: Python vs NumPy**

In [ ]:
import numpy as np

# 1) array of zeros
py_zeros = [0] * 10
np_zeros = np.zeros(10)
print("Python:", py_zeros)
print("Numpy:", np_zeros)

# 2) array of ones
py_ones = [1] * 10
np_ones = np.ones(10)
print("Python:", py_ones)
print("Numpy:", np_ones)

# 3) array of fives
py_fives = [5] * 10
np_fives = np.full(10, 5, dtype=float)
print("Python:", py_fives)
print("Numpy:", np_fives)

# 4) array of zeroes, the fifth value of which is 1
py_zeros_fifth_one = [0] * 10
py_zeros_fifth_one[4] = 1

np_zeros_fifth_one = np.zeros(10, dtype=float)
np_zeros_fifth_one[4] = 1
print("Python:", py_zeros_fifth_one)
print("Numpy:", np_zeros_fifth_one)

# 5) array of all the integers from 10 to 50
py_10_to_50 = list(range(10, 51))
np_10_to_50 = np.arange(10, 51)
print("Python:", py_10_to_50)
print("Numpy:", np_10_to_50)

# 6) array of all the even integers from 10 to 50
py_even_10_to_50 = list(range(10, 51, 2))
np_even_10_to_50 = np.arange(10, 51, 2)
print("Python:", py_even_10_to_50)
print("Numpy:", np_even_10_to_50)

# 7) array that is the reversal of the list [1, 2, 3]
py_list = [1, 2, 3]
py_rev_slice = py_list[::-1]
py_rev_method = list(reversed(py_list))

np_arr = np.array([1, 2, 3])
np_rev_slice = np_arr[::-1]
np_rev_func = np.flip(np_arr)
print("Python:", py_rev_method)
print("Numpy:", np_rev_func)

# 8) a 3x3 matrix with values ranging from 0 to 8
py_matrix_3x3 = [[0, 1, 2],
                 [3, 4, 5],
                 [6, 7, 8]]
np_matrix_3x3 = np.arange(9).reshape(3, 3)
print("Python:", py_matrix_3x3)
print("Numpy:", np_matrix_3x3)

# 9) a 3x3 identity matrix
py_identity_3x3 = [[1 if i == j else 0 for j in range(3)] for i in range(3)]
np_identity_3x3 = np.eye(3, dtype=int)
print("Python:", py_identity_3x3)
print("Numpy:", np_identity_3x3)

# 10) a 5x5 matrix with values 1,2,3,4 just below the diagonal
py_5x5 = [[0]*5 for _ in range(5)]
for i, val in enumerate([1, 2, 3, 4], start=1):
    py_5x5[i][i-1] = val

np_5x5 = np.zeros((5, 5), dtype=int)
np.fill_diagonal(np_5x5[1:, :-1], [1, 2, 3, 4])
print("Python:", py_5x5)
print("Numpy:", np_5x5)


Python: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Python: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Numpy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Python: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Numpy: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
Python: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Python: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Numpy: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Python: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
Numpy: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Python: [3, 2, 1]
Numpy: [3 2 1]
Python: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
Numpy: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Python: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
Numpy: [[1 0 0]
 [0 1 0]
 [0 0 1]]
Python: [[0, 0, 0, 0, 0], [1, 

**Task 5: Using only NumPy:**

In [ ]:
import numpy as np

# 1) 5x5 array with 1 on the border and 0 inside
a1 = np.ones((5, 5))
a1[1:-1, 1:-1] = 0
print("Numpy:", a1)

# 2) Add a border filled with 1's on the two sides of array [1, 2, 3]
a2 = np.array([1, 2, 3])
a2_padded = np.pad(a2, pad_width=1, mode="constant", constant_values=1)
print("Numpy:", a2_padded)

# 3) Array of N equally spaced numbers between A and B
# example: 10 equally spaced numbers between 0 and 1
a3 = np.linspace(0, 1, num=10)
print("Numpy:", a3)

# 4) The given 10x10 matrix from 0.01 to 1.00
a4 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print("Numpy:", a4)

# 5) Indices of non-zero elements in [1, 2, 0, 0, 4, 0]
a5 = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(a5)[0]
print("Numpy:", nonzero_indices)


Numpy: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Numpy: [1 1 2 3 1]
Numpy: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Numpy: [[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]
Numpy: [0 1 4]


**Task 6: Use NumPy to generate:**

In [ ]:
import numpy as np

# 1) random number between 0 and 1
r1 = np.random.rand()
print("Random in [0,1]:", r1)

# 2) array of 25 random numbers from standard normal distribution
r2 = np.random.randn(25)
print("\n25 standard normal samples:\n", r2)

# 3) 3x3x3 array with random values from uniform [0,1)
r3 = np.random.rand(3, 3, 3)
print("\n3x3x3 uniform samples:\n", r3)

# 4) 10x10 array with uniform values and its min/max
r4 = np.random.rand(10, 10)
print("\n10x10 uniform array min:", r4.min(), "max:", r4.max())

# 5) random array (size 30, uniform) and its mean
r5 = np.random.rand(30)
print("\nSize-30 uniform array mean:", r5.mean())

# 6) multiply a 5x3 matrix by a 3x2 matrix
m1 = np.random.rand(5, 3)
m2 = np.random.rand(3, 2)
product = m1 @ m2   # or: np.dot(m1, m2)
print("\n5x3 @ 3x2 result shape:", product.shape)
print(product)

Random in [0,1]: 0.5124869181748456

25 standard normal samples:
 [ 0.23930679 -0.60029304  0.57982152  0.26071439 -0.778112    0.83184642
 -1.05195498 -0.07413243 -0.69621696 -1.97866128 -0.20312436  1.03923586
 -1.68553581  0.21682767 -0.18324811 -0.27588645 -0.98221133 -0.86153025
  1.22983575 -0.58381281 -0.05496394 -0.91464501 -1.22896365  1.40405398
 -1.28157722]

3x3x3 uniform samples:
 [[[0.91268805 0.95426081 0.49903658]
  [0.64999085 0.13579767 0.7391364 ]
  [0.04673197 0.7450425  0.71577355]]

 [[0.71491147 0.96654626 0.21341157]
  [0.95050373 0.48279944 0.53975716]
  [0.24071126 0.11455545 0.3407007 ]]

 [[0.19775431 0.79593628 0.13800795]
  [0.98982119 0.14116428 0.63504609]
  [0.9833583  0.13741585 0.3882194 ]]]

10x10 uniform array min: 0.015915324407069997 max: 0.973460380896404

Size-30 uniform array mean: 0.4849310261262236

5x3 @ 3x2 result shape: (5, 2)
[[0.67533927 0.94898372]
 [0.4791343  0.67376889]
 [0.26444242 0.35350405]
 [0.51946038 0.76399894]
 [0.17872923 0

**Task 7: Write code that uses the below matrix to reproduce the expected output**

In [ ]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

# 1) submatrix
res1 = mat[2:, 1:]
print(res1)

# 2) single element 20
res2 = mat[3, 4]
print(res2)

# 3) column vector [[2],[7],[12]]
res3 = mat[0:3, 1:2]
print(res3)

# 4) last row
res4 = mat[4, :]
print(res4)

# 5) last two rows
res5 = mat[3:, :]
print(res5)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
20
[[ 2]
 [ 7]
 [12]]
[21 22 23 24 25]
[[16 17 18 19 20]
 [21 22 23 24 25]]


**Task 8: Continue using the matrix mat to calculate the:**

In [ ]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

# sum of its values
total_sum = mat.sum()
print(total_sum)

# standard deviation of its values
std_val = mat.std()
print(std_val)

# sum of all the columns
col_sums = mat.sum(axis=0)
print(col_sums)


325
7.211102550927978
[55 60 65 70 75]


**Task 9: Let's practice composing operations:**

In [ ]:
import numpy as np

# 1) 1D array of random ints between -10 and 10; negate those in [3, 8]
arr1 = np.random.randint(-10, 11, size=10)
arr1[(arr1 >= 3) & (arr1 <= 8)] *= -1
print(arr1)

# 2) random float array of size 10, sorted
arr2 = np.random.rand(10)
arr2_sorted = np.sort(arr2)
print(arr2_sorted)

# 3) random uniform vector of size 10, replace max with 0
vec = np.random.rand(10)
print("The array:", vec)
vec[vec.argmax()] = 0.0
print("Result:", vec)


[-8  9  9  1  9 10 -9 -4 -2 -4]
[0.03157303 0.25827964 0.30559399 0.37628351 0.41387007 0.43545752
 0.50974639 0.86799343 0.93869135 0.99145209]
The array: [0.92282964 0.04395705 0.48384511 0.22439829 0.69840894 0.32661725
 0.15079541 0.24094385 0.78224833 0.73457746]
Result: [0.         0.04395705 0.48384511 0.22439829 0.69840894 0.32661725
 0.15079541 0.24094385 0.78224833 0.73457746]


**Task 10: Reproducibility**

In [3]:
#Example 1: Using np.random.seed (legacy global RNG)
#Machine A

import numpy as np

np.random.seed(123)
print(np.random.rand(3))
print(np.random.randint(0, 10, 3))

#Machine B
import numpy as np

np.random.seed(123)
print(np.random.rand(3))
print(np.random.randint(0, 10, 3))

#Example 2: Using default_rng (recommended Generator API)
#Machine A

import numpy as np

rng = np.random.default_rng(123)
print(rng.random(3))
print(rng.integers(0, 10, size=3))

#Machine B

import numpy as np

rng = np.random.default_rng(123)
print(rng.random(3))
print(rng.integers(0, 10, size=3))


[0.69646919 0.28613933 0.22685145]
[6 1 3]
[0.69646919 0.28613933 0.22685145]
[6 1 3]
[0.68235186 0.05382102 0.22035987]
[2 1 3]
[0.68235186 0.05382102 0.22035987]
[2 1 3]
